export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCESS = "LOGIN_SUCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";


export const LOGOUT_SUCESS = "LOGOUT_SUCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const UPDATE_PROFILE_REQUEST="UPUDATE_USER_PROFILE";
export const UPDATE_PROFILE_SUCESS="UPUDATE_USER_SUCESS";
export const UPDATE_PROFILE_RESET="UPUDATE_USER_RESET";
export const UPDATE_PROFILE_FAIL="UPUDATE_USER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCESS = "LOAD_USER_SUCESS";
export const LOAD_USER_FAIL= "LOAD_USER_FAIL";
    
export const CLEAR_ERRORS = "CLEAR_ERRORS";